/** ISO 3166-1 alpha-2 → ISO 4217 currency code */
export const COUNTRY_CURRENCY_MAP: Record<string, string> = {
  SE: "SEK",
  NO: "NOK",
  DK: "DKK",
  FI: "EUR",
  DE: "EUR",
  FR: "EUR",
  NL: "EUR",
  BE: "EUR",
  AT: "EUR",
  ES: "EUR",
  IT: "EUR",
  PT: "EUR",
  IE: "EUR",
  GR: "EUR",
  PL: "PLN",
  CZ: "CZK",
  HU: "HUF",
  CH: "CHF",
  GB: "GBP",
  US: "USD",
  CA: "CAD",
  AU: "AUD",
  NZ: "NZD",
  JP: "JPY",
  CN: "CNY",
  IN: "INR",
  BR: "BRL",
  ZA: "ZAR",
  AE: "AED",
  SA: "SAR",
  NG: "NGN",
  KE: "KES",
  GH: "GHS",
  MA: "MAD",
  EG: "EGP",
  TR: "TRY",
  RU: "RUB",
  MX: "MXN",
  AR: "ARS",
  CO: "COP",
  SG: "SGD",
  HK: "HKD",
  TH: "THB",
  MY: "MYR",
  ID: "IDR",
  PH: "PHP",
  PK: "PKR",
};

export function currencyForCountryCode(code: string | null | undefined): string {
  if (!code) return "SEK";
  return COUNTRY_CURRENCY_MAP[code.toUpperCase()] ?? "SEK";
}
